### ISSUE TITLE
INSERT A FRAMERATE AND CONFIRM WITH "ENTER"

### ISSUE THREAD

**Issue by scottstensland** [SimonWaldherr/cgolGo#1]
I am attempting to execute the start.sh
after installing your repo on ubuntu 16.04
This machine has go properly installed and its graphics libs setup
Did not attempt to troubleshoot this however giving you this feedback
might help 

```
stens@bodhisattva ~/other_src/gopath/src/github.com/SimonWaldherr/cgolGo $ ./start.sh 
INSERT A FRAMERATE AND CONFIRM WITH "ENTER" [15]
./start.sh: 4: read: Illegal option -s
PRESS "R" FOR A RANDOM MAP OR "F" TO LOAD FROM A FILE [R]
./start.sh: 7: read: Illegal option -n
./start.sh: 9: [: unexpected operator
./start.sh: 14: [: unexpected operator
./start.sh: 19: [: unexpected operator
./start.sh: 19: [: unexpected operator
./start.sh: 22: [: unexpected operator
./start.sh: 22: [: unexpected operator

```

ideas ?

**Comment by SimonWaldherr** [comment]
hi @scottstensland, please test it again.
sorry for the late response.

**Comment by scottstensland** [comment]
Solved  !    nicely done

**Comment by SimonWaldherr** [comment]
is there a reason you reopened the issue again?

**Comment by scottstensland** [comment]
no ... just so you can see my acknowledgement the fix worked ... thanks again

**Comment by SimonWaldherr** [comment]
thanks :)
